### ISSUE TITLE
Error trying to reach my server without accept-language

### ISSUE THREAD

**Issue by cloud-walker** [tinganho/express-request-language#8]
If I try to `curl http://localhost:3000` my server, I get this error:

```
TypeError: Cannot read property 'split' of undefined
  at parseAndSortLanguageTags (.../node_modules/accept-language/Build/Source/AcceptLanguage.js:81:40)
  at AcceptLanguage.parse (.../node_modules/accept-language/Build/Source/AcceptLanguage.js:42:43)
  at AcceptLanguage.get (.../node_modules/accept-language/Build/Source/AcceptLanguage.js:36:21)
  at set (.../node_modules/express-request-language/index.js:23:46)
  at .../node_modules/express-request-language/index.js:116:5
  at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (.../node_modules/express/lib/router/index.js:312:13)
  at .../node_modules/express/lib/router/index.js:280:7
  at Function.process_params (.../node_modules/express/lib/router/index.js:330:12)
  at next (.../node_modules/express/lib/router/index.js:271:10)
```

This error is new and I suspect is introduced by the recent work on the sub-package `node-accept-language`.

I don't know the best solution, but I personally think that the middleware should fallback to the default locale if no accept-language header is found. Let me know what you think!

**Comment by tinganho** [comment]
@cloud-walker this is indeed a bug. I updated `node-accept-langauge`. Could you please try again?

**Comment by Asthor** [comment]
Can you update version in package json for node-accept-langauge and make a new tag please?

**Comment by tinganho** [comment]
@Asthor that has already been done?
